# action.yml
name: cosign-installer
author: sigstore
description: 'Installs cosign and includes it in your path'
branding:
  icon: 'package'
  color: 'blue'
# This is pinned to the last major release, we have to bump it for each action version.
inputs:
  cosign-release:
    description: 'cosign release version to be installed'
    required: false
    default: 'v3.0.5'
  install-dir:
    description: 'Where to install the cosign binary'
    required: false
    default: '$HOME/.cosign'
  use-sudo:
    description: 'set to true if install-dir location requires sudo privs'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    # We verify the version against a SHA **in the published action itself**, not in the GCS bucket.
    - shell: bash
      env:
        input_cosign_release: ${{ inputs.cosign-release }}
        input_install_dir: ${{ inputs.install-dir }}
        input_use_sudo: ${{ inputs.use-sudo }}
        runner_arch: ${{ runner.arch }}
        runner_os: ${{ runner.os }}
      run: ${{ github.action_path }}/action.sh

    - if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      shell: bash
      env:
        input_install_dir: ${{ inputs.install-dir }}
      run: envsubst <<<"${input_install_dir}" >> "$GITHUB_PATH"

    - if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      env:
        input_install_dir: ${{ inputs.install-dir }}
      run: |
        $install_dir = $ExecutionContext.InvokeCommand.ExpandString("${env:input_install_dir}")
        echo "${install_dir}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
